### ISSUE TITLE
大骗子，男人没有一个靠得住

### ISSUE THREAD

**Issue by pmeiyu** [sadhen/.emacs.d#1]
上学期你安利我用`helm`，今天我把自己的`.emacs`推到Github之后想看看你的`.emacs.d`长什么样。
打开`sadhen/.emacs.d/`第一眼就看到 `snippets/go-mode    remove buggy helm, use ido  3 days ago`！:broken_heart: 
啊，大骗子，你们男人都喜欢花言巧语。这才多久你就背叛了`helm`，果然男人没有一个靠得住。

海誓山盟，以为可以相聚到海枯石烂。

**Comment by da-liii** [comment]
peng兄，吓坏小弟了

**Comment by da-liii** [comment]
helm和ido是功能类似。但是ido更加稳定一些，而且Emacs已经内置，所以弃用helm，改用ido
